theme: jekyll-theme-minimal
logo: https://preview.redd.it/qz62vwin9ea31.jpg?auto=webp&s=4f184f8618233b6b5dcf57092ffb947c1cd50046
logo: https://i.imgflip.com/4i4i9h.png
title: Introduction to bioinformatics :D
